In [1]:
a = """hii
my name is rohit"""

# remove space lstrip to rstrip using 
s = " hello "
print(s.strip())  
# output -hello 
print(s.lstrip())
# -Hello -
print(s.rstrip())
# -Hello -


s= "spple, banana, grape"
print(s.split(','))
fruits = ['apple','banana']
print(",".join(fruits))

# s = "python Programming"
# print(s.find('Prog')) 
# predefined value is -1 return 

# print(s.index('Prog')) 
# substring not found 
# positive way output is same 

# s = "bad boy"
# print(s.replace("bad","good","good","girl"))
# replace old string to new string count
# print(s.replace("bad","good",2)

# s = "hello world"
# print(s.startwith("hello"))
# print(s.endswith("world"))

# q = "Hello"
# for char in q:
#     print(char)
            
print("python".isalnum())
print("python".isalpha())
print("123".isdigit())

hello
hello 
 hello
['spple', ' banana', ' grape']
apple,banana
True
True
True


In [2]:
# tuple = (1,2,3,4,5,6,7,2,2)
# tuple.count(2)
# tuple.index(3)

# t = int(input("))

print("python".swapcase())
print("hello world".title())
# basically title swap letter swap capital to small 

# s = "python"
# print(s[::-1]) 

help(str.swapcase)

              

PYTHON
Hello World
Help on method_descriptor:

swapcase(self, /)
    Convert uppercase characters to lowercase and lowercase characters to uppercase.



In [3]:
s = "python"
print(s[::2])


pto


In [4]:
s = "python"
print(s[::-1])

nohtyp


In [5]:
a = "madrid"
i = 2;

# a --- [2:]drid 
# a [2:]

# right 
print(a[0:2])
print(a[2:])
print(a[2:]+a[0:2])

# left 
print(a[2:])
print(a[:2])
print(a[2:]+a[:2])


ma
drid
dridma
drid
ma
dridma


In [6]:
string=input("enter your string")
digit=int(input("from where you want your cursor"))
pos=input("enter you want it is right or left").lower()

if len(string)>digit:
    if(pos=="right":
        print(string1(digit:))
       

SyntaxError: invalid syntax (3187065217.py, line 6)

In [ ]:
def functionname(p1,p2,p3)

In [ ]:
def armstrong(n):
    a=0
    b=[]
for i in range(11,n+1):
    print(i)
    l=len(str(i))
    print(l)
    for j in str[i]:
        a+=int(j)**(l)
        print(a)
        if a==i:
            b.append(i)
    return b



In [ ]:
def armstrong(n):
    b = []
    for i in range(11, n+1):
        a = 0
        l = len(str(i))
        for j in str(i):
            a += int(j) ** l
        if a == i:
            b.append(i)
    return b

# Example usage
result = armstrong(500)
print(result)  # Output: [153, 370, 371, 407]


In [ ]:
Q1.Write a Python function find_longest_word that takes a list of words and returns the longest word along with its length.
    
Q2.Write a Python function remove_duplicates that takes a list and returns a new list with duplicates removed, preserving the original order.
Q3.Write a Python function fizz_buzz that takes an integer n and returns a list of strings with the numbers from 1 to n, but for multiples of three it returns "Fizz" instead of the number and for the multiples of five it returns "Buzz". For numbers which are multiples of both three and five, return "FizzBuzz".
Q4.Write a Python function sum_of_digits that takes an integer and returns the sum of its digits.

In [ ]:
# a = [1,2,3,4,5,6,7,8,9,11,12,13,14,15,16]
# b = ''

def sumfunction(n):
    n = abs(n)
    total=0
    while n>0:
        total+=n%10
        n//=10
        return total



In [ ]:
list = [1, 2, 2, 6, 3, 4, 4, 5]
check = []
for item in list:
    # print(item)
    if item not in check:
        # print(item)
        check.append(item)
print(check)

In [ ]:
words_list = ["apple", "banana", "cherry", "blueberry"]
def find_longest_word(words):
    lword = ""
    mword = 0
    
    for word in words:
        if len(word) > mword:
            lword = word
            mword = len(word)
    return lword, mword


longest, length = find_longest_word(words_list)
print(f"The longest word is '{longest}' with length {length}.")

In [ ]:
Write a Python function sum_of_digits that takes an integer and returns the sum of its digits.


In [ ]:
a =[]

In [ ]:
# def fizz_buzz(n):
#     result = []
#     for i in range(1, n+1):
#         if i % 3 == 0 and i % 5 == 0:
#             result.append("fizzbuzz")
#         elif i % 3 == 0:
#             result.append("fizz")
#         elif i % 5 == 0:
#             result.append("Buzz")
#         else:
#             result.append(str(i))
#     return result
    
#     print(fizz_buzz(15))
            

In [ ]:
def fizz_buzz(n):
    result = []
    for i in range(1, n+1):
        # print(i)
        if i % 3 == 0 and i % 5 == 0:
            result.append("fizzbuzz")
        elif i % 3 == 0:
            result.append("fizz")
        elif i % 5 == 0:
            result.append("Buzz")
        else:
            result.append(str(i))
    return result  

# To check the output
print(fizz_buzz(15))


In [ ]:
def fizz_bizz(n):
    result = []
    for i in range(1, n+1):
        print(i)
        if i % 3 == 0 and i % 5 == 0:
           lresult.append("fizz_Buzz")
        elif i % 3 == 0:
            result.append("fizz")
        elif i % 5 == 0:
            result.append("Buzz")
        else:
            result.append(str(i))
        return result
    print(fizz_buzz(15))
    

In [ ]:
a = ['this','is','a','happy','place','to','studey']
longest_word =''
for i in a:
    # if len()
if len(longest_word)<len(a[i]):
    
    # longest_word=a[i]

In [ ]:
the continue statement to skips 

In [ ]:
break continue pass related question  
for number in range(0,10)
pirnt(number)
    if number == 5:
        break

for number in range(10):
    if number % 2 ==0:
        continue 
print(numeber)

for number in range(5):
    if number%2==0:
        pass
    else:
        print(f"{number}-is odd")


In [ ]:
valid_input = {"yes","no","maybe"}
while True:
    user_box = input("Enter 'yes','no', or 'maybe' (type'exit' to quit):")

if user_box == "exit":
    print("Exiting....")
    break
elif user_box not in valid_input:
    print("Invalid input, please try again")
    continue 
else:
    pass

In [11]:
n=200
for j in range(2,n+1):
    for i in range(2,int(j**0.5)):
        if (j%i)==0:
            break
        print(j,"is a prime number")
        


9 is a prime number
11 is a prime number
13 is a prime number
15 is a prime number
17 is a prime number
17 is a prime number
19 is a prime number
19 is a prime number
21 is a prime number
23 is a prime number
23 is a prime number
25 is a prime number
25 is a prime number
25 is a prime number
27 is a prime number
29 is a prime number
29 is a prime number
29 is a prime number
31 is a prime number
31 is a prime number
31 is a prime number
33 is a prime number
35 is a prime number
35 is a prime number
35 is a prime number
37 is a prime number
37 is a prime number
37 is a prime number
37 is a prime number
39 is a prime number
41 is a prime number
41 is a prime number
41 is a prime number
41 is a prime number
43 is a prime number
43 is a prime number
43 is a prime number
43 is a prime number
45 is a prime number
47 is a prime number
47 is a prime number
47 is a prime number
47 is a prime number
49 is a prime number
49 is a prime number
49 is a prime number
49 is a prime number
49 is a prime 

In [ ]:
file handling in python is an essentials skill for dealing with files sucs as text files CSV and more i'LL cover all the key conecpt and functions in file handling in python, including writing appending and managing different types files.

In [6]:
file = open('example.txt','r')
file.close()
# with open()

In [12]:
with open('example.txt','r') as file:
       pass

In [20]:
with open('example.txt','r') as file:
    content = file.read(10)
    print(content)

hello world
hel


In [17]:
with open('example.txt','r') as file:
    first_line = file.readline()
    print(first_line)

hello world



In [18]:
with open('example.txt','r') as file:
    first_line = file.readlines()
    print(first_line)

['hello world\n', 'hello world\n', 'hello world\n', 'hello world\n', 'hello world\n', 'hello world\n', 'hello world\n', 'hello world\n', 'hello world\n', 'hello world\n', 'hello world\n', 'hello world\n', 'hello world\n', 'hello world\n', 'hello world\n', 'hello world\n', 'hello world\n', '\n', '\n', '\n', 'hello worldhello world']


In [32]:
lines = ["Hello\n", "pyhon for Data Science\n","This is a practise fine.\n"]
with open('example.txt','a') as file:
    file.writelines(lines)
    # print(lines)


lines = ["Hello\n", "pyhon for Data Science\n","This is a practise fine.\n"]
with open('example.txt','w') as file:
    file.writelines(lines)
    # print(lines)


In [29]:
with open('example.txt','w+') as file:
    file.write("Hello world")
    print(file.read(10))
    file.close()


In [26]:
lines = ["hello, python\n","solve this quest.\n"]
with open('python_file.txt','w') as file:
    file.writelines(lines)

In [ ]:
with open('image.jpg','rb') as file:
    content = file.read()

with open('image.jpg','wb') as file:
    content = file.read()

In [34]:
with open('python_file.txt','r') as file:
    file.seek(2)
    contents = file.read(3)
    print(contents)

llo


In [1]:
try:
    with open('non_existent.txt','r') as file:
        content = file.read()
except FileNotFoundError:
    print("The file does not exist.")
except IDError:
    print("An I/o error occured")
else:
    print("the file is opened successfully")
finally:
    print("the code is executed")

The file does not exist.
the code is executed


In [4]:
import time
st = time.time()
for i in range(1,10000):
    a=i**2
et=time.time()
exec = et-st
print(f"the timw taken for the execution if the loop {exec: 4f}")

the timw taken for the execution if the loop  0.006618


In [ ]:
file name Return the 
list occupy space 
array memory management is one of the best 
converse a list

In [6]:
firstno = input("enter your first number")
secondno = input("enter your second number")

firstno = int(firstno)
secondno = int(secondno)

final = "";
if final == str(firstno+secondno):
    # print("sum of the number {firstno+secondno}")
    print(f"Sum of the numbers: {firstno + secondno}")
elif final == str(firstno-secondno):
     print("substract the number {firstno-secondno}")
elif final == str(firstno*secondno):         
      print("Multiply the number {firstno*secondno}")   
elif final == str(firstno%secondno):         
      print("Divisible the number {firstno%secondno}") 
else:
    print("nothing happen");

enter your first number 5
enter your second number 5


nothing happen


In [35]:
for i in range(1, 101):
    list = []
    for j in range(1,i):
        if(i % j == 0):
            list.append(j)

    if(sum(list) == i):
        print(f"perfect number {i}")
            

perfect number 6
perfect number 28


In [37]:
for i in range(1,6):
    print('*' *i)

*
**
***
****
*****


In [62]:
def permutation(n, r):
    num = 1 
    den = 1
    for i in range(1,n+1):
        num*=i
    for j in range(1,(n-r)+1):
        den*=j
    a = (num/den)
    print(f"your permutation total is{a}")
   


In [64]:
 permutation(9,3)

your permutation total is504.0


In [4]:
!pip install numpy


In [10]:
import numpy as np

In [16]:
a = np.array([1,2,3,4,5,6])
print(a)
a.ndim 
# no of dimensions # showing dimension

[1 2 3 4 5 6]


1

In [26]:
a = np.array([[1,2,3],[1,2,3],[1,2,3]])
print(a)
a.ndim
b = np.array([[1,2],[1,2],[1,2]])
print(b)
b.ndim
a.shape
a.size
a.dtype
#def infoabtarray(arr):
    #print(f"array shape is {a.shape}")

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 2]
 [1 2]
 [1 2]]


dtype('int32')

In [32]:
b = np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])

a = np.array([[1,2,3,4],[4,5,6,7,5],[8,9,10,11,5]])
print(a)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [36]:
a=np.array([[1,2,3,4,5],
      [7,8,9,10,11],
      [12,13,14,15,16],
      [17,18,19,20,21]
      ])
a[0,[2,4]]


array([3, 5])

In [44]:
#rows or columns = items is 3d third dimension
a = np.array([[
        [1,2,3],
        [4,5,6],
        [7,8,9]],
        [
            [10,11,12],
            [13,14,15],
            [16,17,18]
        ]])
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [24]:
#4d array
#P.I,R,C
import numpy as np
a=np.array([[
    [1,2,3,4],
    [4,5,6,7]
],   [
    [1,2,3,4],
    [4,5,6,7]         
]])
print(a)

[[[1 2 3 4]
  [4 5 6 7]]

 [[1 2 3 4]
  [4 5 6 7]]]


In [44]:
#1d array#
d1=np.array([1,2,3,4])
#d1.ndim


In [50]:
d1+d2

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [48]:
#2d array
d2=np.array([
    [1,2,3,4],
    [5,6,7,8]
])
#d1.ndim
#d1.shape
#d1.size#


In [52]:
#3d array
d2+d1

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [56]:
#3dd
d3=np.array([

    [
        [1,2,3,4],
        [5,6,7,8]
    ],
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
])

In [61]:
d4 = np.array(
 [
    [

    [
        [1,2,3,4],
        [5,6,7,8]
    ],
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
],
    [

    [
        [1,2,3,4],
        [5,6,7,8]
    ],
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
]
    
])

In [63]:
d4.shape

(2, 2, 2, 4)

In [65]:
d5 = np.array(
    [
       [
    [

    [
        [1,2,3,4],
        [5,6,7,8]
    ],
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
],
    [

    [
        [1,2,3,4],
        [5,6,7,8]
    ],
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
]
    
],
               [
    [

    [
        [1,2,3,4],
        [5,6,7,8]
    ],
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
],
    [

    [
        [1,2,3,4],
        [5,6,7,8]
    ],
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
]
    
]
        
    ])

In [67]:
d5.shape

(2, 2, 2, 2, 4)

In [69]:
#Deep copy in duplicate not change
a=np.array([1,2,3,4,5])
b=a.copy()

In [71]:
a[0]=2
print(a)
print(b)

[2 2 3 4 5]
[1 2 3 4 5]


In [73]:
#shallo copyt()

a=np.array([1,2,3,4,5])
b=a.view()

In [77]:
a[0]=3
print(a)
print(b)

[3 2 3 4 5]
[3 2 3 4 5]


In [93]:
#box = 3

#dropped = 

#third no of box frogs should be less than 0 


for frogs in range(2,100):
    for drop in range(2,100):
        a=2*frogs-drop
        if a<0:
            break
        #2pull drop
        a=2*a-drop
        if a<0:
            break
        #3rd pull drop
        a=2*a-drop
        if a==0:
            print(frogs,drop)
        
    


7 8
14 16
21 24
28 32
35 40
42 48
49 56
56 64
63 72
70 80
77 88
84 96
